### ISSUE TITLE
500 error on Volvo API?

### ISSUE THREAD

**Issue by burtherman** [trympet/homebridge-volvo#17]
I'm getting a 500 error in logs when the Volvo plugin is starting - did something change about their endpoints that is breaking the plugin?

**Comment by burtherman** [comment]
To be more clear, the error I'm getting is {"errorLabel":"InvalidInputCriteria","errorDescription":"The input parameters are invalid"}

**Comment by helangen** [comment]
I have the same

`Failed to start homebridge-volvo with Error: Server responded to https://vocapi.wirelesscar.net/customerapi/rest/v3.0/customeraccounts with status code 500:

    at Response.getBody (/var/lib/homebridge/node_modules/homebridge-volvo/node_modules/http-response-object/lib/index.js:41:23)
    at REST.GetSync (/var/lib/homebridge/node_modules/homebridge-volvo/src/util/rest.ts:64:27)
    at VolvoPlatform.GetVehicleSync (/var/lib/homebridge/node_modules/homebridge-volvo/src/index.ts:60:34)
    at new VolvoPlatform (/var/lib/homebridge/node_modules/homebridge-volvo/src/index.ts:36:27)
    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:379:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/var/lib/homebridge/node_modules/homebridge/src/server.ts:299:29)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:179:12)`
