### ISSUE TITLE
No VIN

### ISSUE THREAD

**Issue by Spacetitox** [trympet/homebridge-volvo#26]
] Failed to start homebridge-volvo with Error: No vehicles found matching the VIN number you provided (YV1XMYEXACTVIN222222).
    at VolvoPlatform.GetVehicleSync (/usr/local/lib/node_modules/homebridge-volvo/src/index.ts:85:11)
    at new VolvoPlatform (/usr/local/lib/node_modules/homebridge-volvo/src/index.ts:36:27)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:350:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:12)

If i don't put my vin same error with (undefined) as the VIN...

My car is a Volvo XC40 full electric P8 . Volvo on call is ok . Homebridge on Rpi3 .

**Comment by mkormendy** [comment]
I am having this exact issue as well.

**Comment by maob84** [comment]
Similar issue here on my side. Volvo On-Call app running, vehicle is Volvo XC60 Recharge. I am in Germany. I have tested with provided VIN and without. With debugging enabled, I see the following output.

`[12/13/2021, 07:47:29] [Volvo XC60] Initializing Volvo accessory...
[12/13/2021, 07:47:29] [Volvo XC60] Starting homebridge-volvo
[12/13/2021, 07:47:31] [Volvo XC60] Got account for XXX@xxx.de
[12/13/2021, 07:47:31] [Volvo XC60] You have 0 vehicle(s) associated with your account.
[12/13/2021, 07:47:34] [Volvo XC60] Failed to start homebridge-volvo with Error: No vehicles found matching
 the VIN number you provided (undefined).`

Any ideas?

**Comment by saltsman** [comment]
Having the same issue. Volvo On-Call app running, vehicle is a 2023 Volvo S60 T8 Recharge located in the US. Will not find the vehicle with VIN or without VIN.  With debugging enabled, I see the following output.

```
[26/11/2022, 17:06:55] [Volvo] Initializing Volvo accessory...
[26/11/2022, 17:06:55] [Volvo] Starting homebridge-volvo
[26/11/2022, 17:06:56] [Volvo] Got account for xxx@xxx
[26/11/2022, 17:06:56] [Volvo] You have 0 vehicle(s) associated with your account.
[26/11/2022, 17:06:56] [Volvo] Failed to start homebridge-volvo with Error: No vehicles found matching the VIN number you provided (undefined).
    at VolvoPlatform.GetVehicleSync (/usr/local/lib/node_modules/homebridge-volvo/src/index.ts:85:11)
    at new VolvoPlatform (/usr/local/lib/node_modules/homebridge-volvo/src/index.ts:36:27)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:378:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:298:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:179:12)
[26/11/2022, 17:06:56] [Volvo] Shutting down homebridge-volvo.
[26/11/2022, 17:06:56] [Volvo] Accessory Volvo returned empty set of services; not adding it to the bridge.
```

**Comment by dmeljon** [comment]
also here. any solution?

**Comment by saltsman** [comment]
I'm not sure Trym is updating the plugin any longer. The last code update was in October 2021. I've thought about digging in to resolve the API issue but don't have much experience.
