### ISSUE TITLE
Failed to start homebridge-volvo with Error: No vehicles found matching 

### ISSUE THREAD

**Issue by Tinout** [trympet/homebridge-volvo#45]
What am I doing wrong? The VIN number is okay, and the app is working on the iphone.

 Does anybody have an idea?

Thanks

[Volvo] Got account for xxxx
[10-2-2024 22:19:21] [Volvo] You have 0 vehicle(s) associated with your account.
[10-2-2024 22:19:21] [Volvo] Failed to start homebridge-volvo with Error: No vehicles found matching the VIN number you provided xxxxx
    at VolvoPlatform.GetVehicleSync (/usr/lib/node_modules/homebridge-volvo/src/index.ts:85:11)
    at new VolvoPlatform (/usr/lib/node_modules/homebridge-volvo/src/index.ts:36:27)
    at /usr/lib/node_modules/homebridge/src/server.ts:379:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:299:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:179:12)

**Comment by boboxx** [comment]
I have the same problem, I'm located in Canada and have a 2024 XC60

**Comment by rvaneeuwijk** [comment]
This plugin worked for me until early 2024. It then stopped working and I have not been able to fix it.
