### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by garfieldhy** [trympet/homebridge-volvo#6]
Hi! I installed the plugin on both Synology Nas Docker or Windows 10, and got the same error, could you help? Thanks!

[2020-7-23 7:35:14 ├F10: AM┤] Loading 1 accessories...
[2020-7-23 7:35:14 ├F10: AM┤] [XC90] Initializing Volvo accessory...
[2020-7-23 7:35:14 ├F10: AM┤] [XC90] Starting homebridge-volvo
[2020-7-23 7:35:14 ├F10: AM┤] [XC90] Failed to start homebridge-volvo with Error: getaddrinfo ENOTFOUND vocapi.truewirelesscar.net
    at extractValue (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge-volvo\node_modules\sync-rpc\lib\index.js:165:19)
    at C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge-volvo\node_modules\sync-rpc\lib\index.js:175:12
    at Object.request (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge-volvo\node_modules\sync-request\lib\index.js:28:15)
    at REST.GetSync (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge-volvo\src\util\rest.ts:58:36)
    at VolvoPlatform.GetVehicleSync (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge-volvo\src\index.ts:60:34)
    at new VolvoPlatform (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge-volvo\src\index.ts:36:27)
    at C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:357:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:330:29)
    at Server.start (C:\Users\10298\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:156:12)
[2020-7-23 7:35:14 ├F10: AM┤] [XC90] Shutting down homebridge-volvo.
[2020-7-23 7:35:14 ├F10: AM┤] [XC90] Accessory Volvo returned empty set of services. Won't adding it to the bridge!

**Comment by chowdarygm** [comment]
came here to post the same issue on Raspberry Pi Homebridge 

[7/23/2020, 11:51:45 AM] [Optimus] Failed to start homebridge-volvo with Error: getaddrinfo EAI_AGAIN vocapi.truewirelesscar.net
    at extractValue (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-rpc/lib/index.js:165:19)
    at /usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-rpc/lib/index.js:175:12
    at Object.request (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-request/lib/index.js:28:15)
    at REST.GetSync (/usr/local/lib/node_modules/homebridge-volvo/src/util/rest.ts:58:36)
    at VolvoPlatform.GetVehicleSync (/usr/local/lib/node_modules/homebridge-volvo/src/index.ts:60:34)
    at new VolvoPlatform (/usr/local/lib/node_modules/homebridge-volvo/src/index.ts:36:27)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:357:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)

**Comment by trympet** [comment]
Hi, thanks for letting me know.

It seems that the API endpoint is returning a 301 redirect when homebridge-volvo sends the initial request to the endpoint `https://vocapi.wirelesscar.net/customerapi/rest/v3.0/`, since there is no reference to the domain `vocapi.truewirelesscar.net` in the entire source code.

**Comment by trympet** [comment]
I presume you live in NA. If so, it should be fixed now in [v1.0.5](https://github.com/trympet/homebridge-volvo/releases/tag/v1.0.5). Otherwise, please let me know :)

**Comment by garfieldhy** [comment]
Yes,in NA. Thank you so much for the fix！Now all the function work except the Climate button. It shows no response in red colour.

**Comment by trympet** [comment]
Okay, thanks for the feedback. I'll look into it 😊

**Comment by Dunlapjc** [comment]
> Yes,in NA. Thank you so much for the fix！Now all the function work except the Climate button. It shows no response in red colour.

Yes, confirmed by a second person.   All is working except for a climate tile/button which shows no response and is red in color.

**Comment by trympet** [comment]
Hi. Could you turn on debug mode and post the output from Homebridge on startup?

**Comment by Dunlapjc** [comment]
Hi,
I’d be happy to.  I’ll research how/where to do that tonight...
It’s been a while since I built my home bridge server on the Pi...   And since I installed the web interface, that’s my default go to for installing new platforms / accessories.

Thanks,
Jonathan

**Comment by trympet** [comment]
Hi, Jonathan. Thanks for the help! You can enable debug mode from the web interface and see the logs by:
1. Logging into the web interface and opening `Homebridge Settings`
![step1](https://user-images.githubusercontent.com/23460729/90525820-f36f5280-e16f-11ea-83bd-5e79ec292a68.png)

2. Enable `Homebridge Debug Mode`
![step2](https://user-images.githubusercontent.com/23460729/90525883-08e47c80-e170-11ea-8d5f-05af7579a082.png)

3. Restart Homebridge and check the logs 
![step3](https://user-images.githubusercontent.com/23460729/90526245-70023100-e170-11ea-8479-600b1a64c7f0.png)

4. Post logs (vehicle attributes and vehicle state)


All sensitive information should automatically be censored, but you could also send me an email if you'd like 😊

**Comment by Dunlapjc** [comment]
Here’s a snapshot of what what the reboot looks like with the debug log…:

Thanks for your work at this!
-Jonathan


[8/19/2020, 9:43:27 PM] [Config] Rebooting linux server with command: "sudo -n shutdown -r now"
[8/19/2020, 9:43:28 PM] [HB Supervisor] Stopping services...
[8/19/2020, 9:43:28 PM] Got SIGTERM, shutting down Homebridge...
[8/19/2020, 9:43:28 PM] [Volvo] Updating...
[8/19/2020, 9:43:33 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/19/2020, 9:43:57 PM] [HB Supervisor] OS: Linux 4.19.97-v7l+ arm
[8/19/2020, 9:43:57 PM] [HB Supervisor] Node.js v12.16.3 /usr/bin/node
[8/19/2020, 9:43:57 PM] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[8/19/2020, 9:43:57 PM] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[8/19/2020, 9:43:57 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[8/19/2020, 9:43:57 PM] [HB Supervisor] Started Homebridge v1.1.2 with PID: 545
[8/19/2020, 9:43:59 PM] Loaded config.json with 1 accessories and 4 platforms.
[8/19/2020, 9:43:59 PM] ---
[8/19/2020, 9:44:01 PM] Loaded plugin: homebridge-aqualinkd@0.0.9
[8/19/2020, 9:44:01 PM] Registering platform 'homebridge-aqualinkd.aqualinkd'
[8/19/2020, 9:44:01 PM] ---
[8/19/2020, 9:44:01 PM] Loaded plugin: homebridge-config-ui-x@4.25.2
[8/19/2020, 9:44:01 PM] Registering platform 'homebridge-config-ui-x.config'
[8/19/2020, 9:44:01 PM] ---
[8/19/2020, 9:44:01 PM] Loaded plugin: homebridge-nest@4.4.6
[8/19/2020, 9:44:01 PM] Registering platform 'homebridge-nest.Nest'
[8/19/2020, 9:44:01 PM] ---
[8/19/2020, 9:44:02 PM] [Config] Homebridge Config UI X v4.25.2 is listening on :: port 80
[8/19/2020, 9:44:02 PM] Loaded plugin: homebridge-smartthings-v2@2.3.4
[8/19/2020, 9:44:02 PM] Registering platform 'homebridge-smartthings-v2.SmartThings-v2'
[8/19/2020, 9:44:02 PM] ---
[8/19/2020, 9:44:03 PM] Loaded plugin: homebridge-volvo@1.0.5
[8/19/2020, 9:44:03 PM] Registering accessory 'homebridge-volvo.Volvo'
[8/19/2020, 9:44:03 PM] ---
[8/19/2020, 9:44:03 PM] Loading 4 platforms...
[8/19/2020, 9:44:03 PM] [Config] Initializing config platform...
[8/19/2020, 9:44:03 PM] [Config] Running in Service Mode
[8/19/2020, 9:44:03 PM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[8/19/2020, 9:44:03 pm] [SmartThings-v2] INFO: Homebridge Version: 2.6
[8/19/2020, 9:44:03 pm] [SmartThings-v2] INFO: SmartThings-v2 Plugin Version: 2.3.4
[8/19/2020, 9:44:03 pm] [SmartThings-v2] INFO: Checking Package Version for Updates...
[8/19/2020, 9:44:03 PM] [Nest] Initializing Nest platform...
[8/19/2020, 9:44:03 PM] [Nest] Fetching Nest devices.
[8/19/2020, 9:44:03 PM] [Nest] Authenticating via access token.
[8/19/2020, 9:44:03 PM] [AqualinkD] Initializing aqualinkd platform...
[8/19/2020, 9:44:03 PM] Loading 1 accessories...
[8/19/2020, 9:44:04 PM] [Volvo] Initializing Volvo accessory...
[8/19/2020, 9:44:04 PM] [Volvo] Starting homebridge-volvo
[8/19/2020, 9:44:04 PM] [Volvo] Got account for dunlapjc@yahoo.com
[8/19/2020, 9:44:04 PM] [Volvo] You have 1 vehicle(s) associated with your account.
[8/19/2020, 9:44:05 PM] [Volvo] Vehicle attributes:
{
  "engineCode": "2411CF0A",
  "exteriorCode": "24111107",
  "interiorCode": "24111027",
  "tyreDimensionCode": "2411R50D",
  "tyreInflationPressureLightCode": null,
  "tyreInflationPressureHeavyCode": null,
  "gearboxCode": "2411DB04",
  "fuelType": "Gasoline",
  "fuelTankVolume": 60,
  "grossWeight": 2420,
  "modelYear": 2018,
  "vehicleType": "V90",
  "vehicleTypeCode": "2411AA03",
  "numberOfDoors": 5,
  "country": {
    "iso2": "US"
  },
  "carLocatorDistance": 1000,
  "honkAndBlinkDistance": 500,
  "bCallAssistanceNumber": "+18553994691",
  "carLocatorSupported": true,
  "honkAndBlinkSupported": true,
  "honkAndBlinkVersionsSupported": [
    "honkAndOrBlink",
    "honkAndBlink"
  ],
  "remoteHeaterSupported": false,
  "unlockSupported": true,
  "lockSupported": true,
  "journalLogSupported": true,
  "assistanceCallSupported": true,
  "unlockTimeFrame": 120,
  "verificationTimeFrame": 120,
  "timeFullyAccessible": 7200,
  "timePartiallyAccessible": 31680,
  "subscriptionType": "PREMIUM_2013",
  "subscriptionStartDate": "2018-02-15T12:00:00+0000",
  "subscriptionEndDate": "2027-02-15T12:00:00+0000",
  "serverVersion": "20.4.9-voc-deployable",
  "journalLogEnabled": true,
  "highVoltageBatterySupported": false,
  "maxActiveDelayChargingLocations": null,
  "preclimatizationSupported": true,
  "sendPOIToVehicleVersionsSupported": [
    "sendSinglePOIToVehicle"
  ],
  "climatizationCalendarVersionsSupported": [
    "climatizationCalendarV1"
  ],
  "climatizationCalendarMaxTimers": 8,
  "vehiclePlatform": "2411",
  "overrideDelayChargingSupported": false,
  "engineStartSupported": true,
  "status.parkedIndoor.supported": false,
  "vin": "***REDACTED***",
  "VIN": "***REDACTED***",
  "registrationNumber": "***REDACTED***"
}
[8/19/2020, 9:44:05 PM] [Volvo] Vehicle state:
{
  "ERS": {
    "status": "off",
    "timestamp": "2020-08-15T19:54:26+0000",
    "engineStartWarning": "None",
    "engineStartWarningTimestamp": "2020-08-15T19:54:26+0000"
  },
  "averageFuelConsumption": 105,
  "averageFuelConsumptionTimestamp": "2020-08-20T01:43:29+0000",
  "averageSpeed": 57,
  "averageSpeedTimestamp": "2020-08-20T01:43:29+0000",
  "brakeFluid": "Normal",
  "brakeFluidTimestamp": "2020-08-20T01:43:29+0000",
  "bulbFailures": [],
  "bulbFailuresTimestamp": "2020-08-20T01:43:29+0000",
  "carLocked": false,
  "carLockedTimestamp": "2020-08-20T01:43:29+0000",
  "distanceToEmpty": 528,
  "distanceToEmptyTimestamp": "2020-08-20T01:43:29+0000",
  "doors": {
    "tailgateOpen": false,
    "rearRightDoorOpen": false,
    "rearLeftDoorOpen": false,
    "frontRightDoorOpen": false,
    "frontLeftDoorOpen": false,
    "hoodOpen": false,
    "timestamp": "2020-08-20T01:43:29+0000"
  },
  "engineRunning": false,
  "engineRunningTimestamp": "2020-08-20T01:43:29+0000",
  "fuelAmount": 57,
  "fuelAmountLevel": 95,
  "fuelAmountLevelTimestamp": "2020-08-20T01:43:29+0000",
  "fuelAmountTimestamp": "2020-08-20T01:43:29+0000",
  "odometer": 48558802,
  "odometerTimestamp": "2020-08-20T01:43:29+0000",
  "privacyPolicyEnabled": false,
  "privacyPolicyEnabledTimestamp": "2019-02-25T15:08:22+0000",
  "remoteClimatizationStatus": null,
  "remoteClimatizationStatusTimestamp": null,
  "serviceWarningStatus": "TimeForService",
  "serviceWarningStatusTimestamp": "2020-08-20T01:43:29+0000",
  "timeFullyAccessibleUntil": "2020-08-24T21:41:43+0000",
  "timePartiallyAccessibleUntil": "2020-09-10T21:41:43+0000",
  "tripMeter1": 12766900,
  "tripMeter1Timestamp": "2020-08-20T01:43:29+0000",
  "tripMeter2": 52900,
  "tripMeter2Timestamp": "2020-08-20T01:43:29+0000",
  "tyrePressure": {
    "frontLeftTyrePressure": "Normal",
    "frontRightTyrePressure": "Normal",
    "rearLeftTyrePressure": "Normal",
    "rearRightTyrePressure": "Normal",
    "timestamp": "2020-08-20T01:43:29+0000"
  },
  "washerFluidLevel": "Normal",
  "washerFluidLevelTimestamp": "2020-08-20T01:43:29+0000",
  "windows": {
    "frontLeftWindowOpen": false,
    "frontRightWindowOpen": false,
    "timestamp": "2020-08-20T01:43:29+0000",
    "rearLeftWindowOpen": false,
    "rearRightWindowOpen": false
  },
  "theftAlarm": "***REDACTED***"
}
[8/19/2020, 9:44:05 PM] [Volvo] 
Features available:
        carLocatorSupported
        honkAndOrBlink
        honkAndBlink
        unlockSupported
        lockSupported
        preclimatizationSupported
        engineStartSupported
[8/19/2020, 9:44:05 PM] [Volvo] 
Features enabled:
        carLocatorSupported
        honkAndOrBlink
        honkAndBlink
        unlockSupported
        lockSupported
        preclimatizationSupported
        engineStartSupported
[8/19/2020, 9:44:05 PM] [Volvo] Got vehicle 2018 V90 with registration number null.
[8/19/2020, 9:44:05 pm] [SmartThings-v2] INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
[8/19/2020, 9:44:05 pm] [SmartThings-v2] GOOD: Refreshing All Device Data | Source: (First Launch)
[8/19/2020, 9:44:05 PM] [AqualinkD] Connecting MQTT broker to 192.168.0.6:1883 with topic aqualinkd
[8/19/2020, 9:44:05 PM] [AqualinkD] Successfully connected to MQTT broker.
[8/19/2020, 9:44:05 PM] [Nest] Auth failed: access token specified in Homebridge configuration rejected
[8/19/2020, 9:44:05 PM] [Nest] Unable to authenticate with Google/Nest.
Setup Payload:
X-HM://0023W1MBZ3JL1
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 253-83-759 │     
    └────────────┘     
                       
[8/19/2020, 9:44:06 PM] Homebridge is running on port 51269.
[8/19/2020, 9:44:07 pm] [SmartThings-v2] INFO: INFO: Your plugin version is up-to-date
[8/19/2020, 9:44:07 pm] [SmartThings-v2] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4
[8/19/2020, 9:44:08 PM] [Volvo] GET heater
[8/19/2020, 9:44:22 PM] [Volvo] GET heater
[8/19/2020, 9:44:22 PM] [Volvo] GET heater
[8/19/2020, 9:44:24 pm] [SmartThings-v2] NOTICE: Temperature Unit is Now: (F)
[8/19/2020, 9:44:24 pm] [SmartThings-v2] NOTICE: Updating Global Values | HubIP: 192.168.0.15 | UseLocal: false
[8/19/2020, 9:44:24 pm] [SmartThings-v2] WARN: Devices to Remove: (0) []
[8/19/2020, 9:44:24 pm] [SmartThings-v2] INFO: Devices to Update: (36)
[8/19/2020, 9:44:24 pm] [SmartThings-v2] GOOD: Devices to Create: (0) []
[8/19/2020, 9:44:24 pm] [SmartThings-v2] ALERT: Total Initialization Time: (19 seconds)
[8/19/2020, 9:44:24 pm] [SmartThings-v2] NOTICE: Unknown Capabilities: ["Momentary","towertalent27877.lastActivity","towertalent27877.connectedSensor","Holdable Button","Relay Switch"]
[8/19/2020, 9:44:24 pm] [SmartThings-v2] INFO: SmartThings DeviceCache Size: (36)
[8/19/2020, 9:44:24 pm] [SmartThings-v2] INFO: WebServer Initiated...
[8/19/2020, 9:44:24 pm] [SmartThings-v2] INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
[8/19/2020, 9:44:24 pm] [SmartThings-v2] INFO: Direct Connect Active | Listening at 192.168.0.5:8000
[8/19/2020, 9:44:24 pm] [SmartThings-v2] INFO: SmartThings-v2 Hub Communication Established
[8/19/2020, 9:44:30 PM] [Volvo] GET blinkActive
[8/19/2020, 9:44:30 PM] [Volvo] GET honkBlinkActive
[8/19/2020, 9:44:30 PM] [Volvo] GET heater
[8/19/2020, 9:44:30 PM] [Volvo] GET ERS
[8/19/2020, 9:44:30 PM] [Volvo] GET carLocked
[8/19/2020, 9:44:30 PM] [Volvo] GET fuelAmountLevel
[8/19/2020, 9:44:30 PM] [Volvo] GET fuelAmountLevelLow
[8/19/2020, 9:44:30 PM] [Volvo] GET engineRunning
[8/19/2020, 9:44:30 PM] [Volvo] GET tailgateOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET rearRightDoorOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET rearLeftDoorOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET frontRightDoorOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET frontLeftDoorOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET rearRightWindowOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET rearLeftWindowOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET frontRightWindowOpen
[8/19/2020, 9:44:30 PM] [Volvo] GET frontLeftWindowOpen
heatingSetpoint:  68
coolingSetpoint:  undefined
heatingSetpoint:  72
coolingSetpoint:  undefined
[8/19/2020, 9:44:33 PM] [Volvo] Updating...
[8/19/2020, 9:44:33 PM] [Volvo] GET blinkActive
[8/19/2020, 9:44:33 PM] [Volvo] GET honkBlinkActive
[8/19/2020, 9:44:33 PM] [Volvo] GET heater
[8/19/2020, 9:44:33 PM] [Volvo] GET ERS
[8/19/2020, 9:44:33 PM] [Volvo] GET carLocked
[8/19/2020, 9:44:33 PM] [Volvo] GET fuelAmountLevel
[8/19/2020, 9:44:33 PM] [Volvo] GET fuelAmountLevelLow
[8/19/2020, 9:44:33 PM] [Volvo] GET engineRunning
[8/19/2020, 9:44:33 PM] [Volvo] GET tailgateOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET rearRightDoorOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET rearLeftDoorOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET frontRightDoorOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET frontLeftDoorOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET rearRightWindowOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET rearLeftWindowOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET frontRightWindowOpen
[8/19/2020, 9:44:33 PM] [Volvo] GET frontLeftWindowOpen
heatingSetpoint:  68
coolingSetpoint:  undefined
heatingSetpoint:  72
coolingSetpoint:  undefined

**Comment by trympet** [comment]
> Agreed. Either the API is different, and/or the the car software itself. For instance, parking climate is in the menus, but doesn’t work in this region... Thanks for your work at this, Jonathan
> […](#)
> Sent from my iPhone
> On Aug 23, 2020, at 10:13 AM, TrymPet ***@***.***> wrote: ﻿ Thanks for your help! Hmm, interesting. It appears that the response is missing the "heater" object and "status" property, which is used for determining if the climate is on or off. This is what it looks like on my end: "heater": { "seatSelection": { "frontDriverSide": false, "frontPassengerSide": false, "rearDriverSide": false, "rearPassengerSide": false, "rearMid": false }, "status": "off", "timer1": { "time": null, "state": null }, "timer2": { "time": null, "state": null }, "timestamp": "2020-08-10T10:50:05+0000" } I was not able to replicate a response without the "heater" object on my end, which could mean that the API differs between different regions (I am EU). — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Does that apply to the official app by Volvo as well?
