### ISSUE TITLE
Got SIGTERM, shutting down ...[Volvo] Failed to update vehicle status from Volvo On Call API.

### ISSUE THREAD

**Issue by DJay-X** [trympet/homebridge-volvo#8]
@trympet  Hey there. I hope you are doing well.

My Homebridge did shut down this morning due to the Volvo Plugin.
After manually restart everything was working again.

However, this error probably shouldn't crash and shutting down the whole homebridge?

Maybe a small fix for a future update.

Thanks again for your time and work. 👍 

```
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]: [2020-8-24 7:29:47] [Volvo] Failed to update vehicle status from Volvo On Call API.
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]: [2020-8-24 7:29:47] Error: send ENETUNREACH 224.0.0.251:5353
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]:     at doSend (dgram.js:683:16)
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]:     at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]:     at afterDns (dgram.js:629:5)
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]:     at processTicksAndRejections (internal/process/task_queues.js:85:21)
Aug 24 07:29:47 raspberrypi-3BPlus homebridge[437]: [2020-8-24 7:29:47] Got SIGTERM, shutting down Homebridge...
```

**Comment by trympet** [comment]
Hi, @DJay-X!

Thanks for you continued feedback, really appreciated 😊

Absolutely correct, an error in a plugin should never shut down the entire Homebridge instance. I think the issue might be related to incorrect HTTP response validation. I'll have a look and see what I find.

**Comment by DJay-X** [comment]
@trympet I hope you are doing well.

Unfortunately another issue with the Volvo plugin that stopped homebridge from working and shutdown.
Maybe it helps to investigate. 

```
[2020-9-24 19:07:50] ERROR LOADING PLUGIN homebridge-volvo:
[2020-9-24 19:07:50] Error: Timed out waiting for sync-rpc server to start (it should respond with "pong" when sent "ping"):
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:41803
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 41803
}
    at waitForAlive (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-rpc/lib/index.js:85:11)
    at start (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-rpc/lib/index.js:41:3)
    at sendMessage (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-rpc/lib/index.js:133:17)
    at createClient (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-rpc/lib/index.js:173:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-volvo/node_modules/sync-request/lib/index.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-volvo/dist/util/rest.js:28:34)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-volvo/dist/util/vehicleApi.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-volvo/dist/util/vehicle.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-volvo/dist/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:124:31)
    at /usr/local/lib/node_modules/homebridge/lib/pluginManager.js:63:24
    at Map.forEach (<anonymous>:null:null)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:61:22)
    at Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:71:28)
    at cli (/usr/local/lib/node_modules/homebridge/lib/cli.js:88:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
